services:

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - app

                             
  app:
    build: 
      context: .
    depends_on: 
      - db  
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    # ports:
    #   - 8000:8000
    volumes:
      - static_data:/vol/web
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    uwsgi --socket :8000 --master --enable-threads --module app.wsgi"                

  db:
    image: postgres:12.17-alpine
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data1  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - PGPORT=${POSTGRES_PORT}

volumes:
  static_data: